name: Build & Release

on:
  push:
    branches:
      - '!*'
    tags:
      - 'v*.*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write

    steps:
      - uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: lts/*
          cache: npm

      - run: npm ci
      - run: npm run build
      - run: npm run package
      - run: npm run manifest

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          name: ${{ github.ref_name }}
          prerelease: false
          draft: false
          allowUpdates: true
          omitNameDuringUpdate: true
          omitBodyDuringUpdate: true
          omitDraftDuringUpdate: true
          omitPrereleaseDuringUpdate: true
          artifacts: '*.ipk'

      - name: Trigger update-repo workflow
        uses: actions/github-script@v8
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'update-repo.yml',
              ref: 'dev'
            })
